WIP: initial POC while watching Solana SMS/Saga video
workbenchapp/solana-workbench pull request #149
Opened 2022-06-24 07:51 UTC by SvenDowideit

* [ ] convert stop container
* [ ] separate into start container, start validator, stop validator, remove container
* [ ] add amman snapshot
* [ ] work out ux for selecting programs to import - using docker copy

2022-07-02 04:49 UTC, SvenDowideit commented
mmm, so in the `npm run dev` console, you can see the `dockerode.pull` handler showing the pull progress, and then create the container - and if you wait, you see the create button get disabled, and the start button enable.

but because the handler is going after the promise returns, the toast completes.

I'd much rather have a promise that waits til the container is created, but i suspect I actually need to implement a manually controlled `toast` that gets updated from the pull handler

2022-07-06 04:07 UTC, SvenDowideit commented
![image](https://user-images.githubusercontent.com/28492/177466180-75739e43-e207-46d0-b46a-658011e6db8a.png)

2022-07-06 04:24 UTC, SvenDowideit commented
Okay!, @nathanleclaire can you please review this - I would like to merge it asap so I can use it for the tokens work.

2022-07-06 23:15 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +  useEffect(() => {
should work if you write the function something like this:

```typescript
useEffect(() => {
  const fn = async() => {
    try {
      const tags = await window.promiseIpc.send(
        'DOCKER-GetImageTags', 
        validatorImageName
      );
      setValidatorImageTags(tags);
    } catch (e) {
      logger.error(e);
    }
  };
  fn();
}, [validatorImageName]);
```

2022-07-06 23:19 UTC, SvenDowideit commented on src/main/ipc/docker.ts
> +    accountsCluster: 'https://api.metaplex.solana.com',
NO? use normal api...

2022-07-06 23:19 UTC, SvenDowideit commented on src/main/ipc/docker.ts
> +        cluster: 'https://metaplex.devnet.rpcpool.com',
same here, use normal solana

2022-07-06 23:30 UTC, nathanleclaire requested changes

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +      {
Maybe add a comment that these are like verification accounts

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +    websocketUrl: '',
should this be set? 'ws://0.0.0.0:8900`

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +      // log(`main: called DOCKER-GetContainerStatus, ${name}, ${event}`);
rm extra comment please ?

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +      log(`request stop: solana-test-validator`);
what's up with these multiple `log` calls?

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +          // logger.info(`INSPECT: ${JSON.stringify(inspect)}`);
rm pls

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +            // if (validator.status === NetStatus.Running) {
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +                // ipcDockerToast('StartAmmanValidator');
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +                    // ipcDockerToast('StartAmmanValidator');
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +                        // ipcDockerToast('StartAmmanValidator');
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +                      // setValidatorImageTags(tags);
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +          // logger.info('log: ', res);
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/renderer/nav/Validator.tsx
> +    // if (validator.status === NetStatus.Running) {
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/validator.ts
> +  // const MAX_TAIL_LINES = 10000;
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +    'DOCKER-GetImageTags',
can merge this in as-is, but in future, can we stick to existing `skewer-case` convention please?

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +        // hijack: true,
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +    // logger.info(`onPullProgress: ${JSON.stringify(_event)}`);
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +  // logger.info(`----------- pullStream ${JSON.stringify(pullStream)}`);
rm

2022-07-06 23:30 UTC, nathanleclaire commented on src/main/ipc/docker.ts
> +        // executable: false,
rm

2022-07-07 01:04 UTC, SvenDowideit commented
Running with it, will work on the other bits post token

2022-07-07 01:04 UTC, merged