show the error output from validatorLogs func in lov viewer
workbenchapp/solana-workbench pull request #98
Opened 2022-05-04 05:22 UTC by SvenDowideit

closes #41

2022-05-04 20:28 UTC, nathanleclaire requested changes

2022-05-04 20:28 UTC, nathanleclaire commented on src/main/validator.ts
> +    return `Cannot show validator container output from ${net}`;
IIRC this should be a proper `throw new Error(`Cannot show validator container output from ${net}`)` and lint might well complain about it

2022-05-04 20:29 UTC, nathanleclaire commented
very nice! appreciate this one as it's been a thorn in my side for ages.

have a couple lint issues build is complaining about, but once those are fixed, lgtm

2022-05-04 22:40 UTC, SvenDowideit commented
I'm going to claim the `console.log` thing is because https://github.com/workbenchapp/solana-workbench/pull/94 isn't merged yet :)

wrt the `throw Error` - exceptions are ... for exception cases, not for normal, detected results - and this is not exceptional.

2022-05-04 23:56 UTC, nathanleclaire commented
> wrt the throw Error - exceptions are ... for exception cases, not for normal, detected results - and this is not exceptional.

either/or, if it's ok with lint, fine by me, just seem to recall my VSCode complaining about it

2022-05-04 23:57 UTC, nathanleclaire commented
now that #94 is in business, lgtm once log lines are updated

2022-05-04 23:57 UTC, nathanleclaire approved these changes

2022-05-05 00:05 UTC, SvenDowideit commented
yeah, that linter error was weird - mixing `return string` and `return { output }` - for now i'm going with just returning a string, and showing that in the UI - atm some point, I hope to upgrade the ipc code to something typed - that thunking makes me cringe like its 1996

2022-05-05 00:05 UTC, merged